### PR TITLE
Game implemented

### PR DESCRIPTION
**Pull request by petinhoss7**
Need to fix bugs + translations

### CODE REVIEW

**Comment by schwabdidier** [comment]
Please,next time,one feature one branch and one pull request.
one new game, one branch
one feature, one branch (eg. a brach for keyconfiguration)

**Comment by schwabdidier** [comment]
There is a strong problem with this pull request (delete multilingualism.csv)

**Comment by petinhoss7** [comment]
@schwabdidier What is wrong with multilinguism.csv? should i delete it and do the pull request again?

**Comment by schwabdidier** [comment]
You delete it in your pull request.

**Comment by schwabdidier** [comment]
So resolve the problem and make a new pull request

**Pull request merged**
