### PR TITLE
Color Game finish

### PR DESCRIPTION
**Pull request by WaffleBuffer**
I think that the color game is in a good state to be considered "realesable". If there is any problem open an issue.

### CODE REVIEW

**Comment by schwabdidier** [comment]
@YannRobert will check changes

**Comment by YannRobert** [comment]
Please rebase from master
Please squash your commits to just 1 or 2.

You don't need 23 commits in this pull request. The diff is unreadable as is.
a PR needs to be as small as possible, to make it easy to track what as been changed, and why it has been changed.

The diff should not include changes from other PR that where made in the meantime. This is really important.

Please refer to documentation (stackoverflow or anything) to see how you can perform a squash during a rebase with git.

Once you have rebased your local branch, you force push to github. 

Also please clean up your changes, so that you change only what is needed to be changed to reach the goal of the PR.
For instance :
This is disturbing to have multiple lines changed in gitignore when you only needed to add 1 line.
This is an illustration on how small the diff should be. If you intend to add 1 line, then just 1 line should be added.

Similarly :
If you intend to work on the color game then only this game should be changed. 

Generally : Refrain from changing too many things in the same commit. Refrain to change multiple things in the same PR.

If you don't manage to do the rebase and squash, please tell me so that I can help.

**Comment by WaffleBuffer** [comment]
Oh, something i didn't notice is when i push to my master, it automatically add it to the PR. That is not something i wanted. I will create some branches from the commits i wanted to PR originally and leave master alone.

**Comment by YannRobert** [comment]
I guess people have been there already, so you may find the answer on stackoverflow.

**Comment by YannRobert** [comment]
Start by a rebase. The branch is not important for the moment. Only the content is important.
But this illustrate your should never commit to master.

**Pull request closed without merging**
