### PR TITLE
New Button for ControlPanel

### PR DESCRIPTION
**Pull request by kuhlkrein**
Only mousse clickable button. It open the controlPanel.
@schwabdidier , @YannRobert , here is a solution for the controlPanel, what do you think ?
#400 
#395

### CODE REVIEW

**Comment by schwabdidier** [comment]
I like it.

**Comment by kuhlkrein** [comment]
Sry I didn't noticed there was a second conflict.

**Comment by schwabdidier** [comment]
@YannRobert any comment ?

**Comment by kuhlkrein** [comment]
I'm trying to solve all the conflicts problems

**Pull request merged**
