### PR TITLE
Modifications in order to make the gazemenu usable.

### PR DESCRIPTION
**Pull request by kuhlkrein**
I change the refresh time of abstractgazedevicemanager to a lower value
so that it will not throw unexpected exeption. 25 instead of 10 seems to
be good. I also tried with 50 but it's maybe a bit too much for some
games

### CODE REVIEW

**Comment by schwabdidier** [comment]
With 25 ms, it means that eye-tracker Frequency is only 40 Hz instead of 90 Hz. Maybe, you can try 12-15 (83-66Hz) ?

**Comment by kuhlkrein** [comment]
Ok I'll try thanks !

**Comment by kuhlkrein** [comment]
it works with 20 but not with 15... maybe what I can do is use 20 only if the gazemenu is activated ?

**Comment by kuhlkrein** [comment]
hum no it's not possible

**Comment by schwabdidier** [comment]
Ok, do it but report an issue. It would be good to find how to resolve that.

**Pull request merged**
