### PR TITLE
Added new Game Math101

### PR DESCRIPTION
**Pull request by wafaahs**
Added new Game Math 101 
Added Labels to multilinguism with translations

### CODE REVIEW

**Comment by schwabdidier** [comment]
I am currently checking it. 

Next time please use a branch to resolve the problem (wafaa/local-math-game for instance) instead of master

**Comment by wafaahs** [comment]
Screen Shot 2019-04-06 at 12 56 57 PM


Dr. What problem are you referring to? I am confused.. Because now everything seems to be fine.

**Comment by schwabdidier** [comment]
@wafaahs nice work ! I merge and I will add some issues

**Comment by schwabdidier** [comment]
The only "problem" is the name of the branch of the pull request (local-math-game would be better than the master, it is more informative)

**Comment by schwabdidier** [comment]
I really like Graphic design

**Comment by wafaahs** [comment]
Oh okay! Noted and  will make a new branch next time. 
Thank you Dr.

**Pull request merged**
