### PR TITLE
Ready to be merged : Separate the zone used for command and control, from the zone used for game

### PR DESCRIPTION
**Pull request by YannRobert**
using a BorderPane in order to separate the zone used for command and control, from the zone used for displaying the game itself

### CODE REVIEW

**Comment by YannRobert** [comment]
Hi @schwabdidier what do you think of this so far ? 

There is still an issue with the detection of the size of the center game panel on the first round.
Subsequent rounds are properly using the exact panel size. But the first round is using an approximation of it.

I would have like to fix this; 
but maybe we can merge first, as this is still playable IMO, and provides a lot of improvements.

Can you find any other issue in the PR ?

**Comment by schwabdidier** [comment]
I like it very much. I shown it to my wife and Loïc, they also liked it.

One problem I have seen. With statistics, we can click on diagram to see them bigger. It works very bad, the diagrams move randomly in the screen.

**Comment by schwabdidier** [comment]
I can merge if you wish, the problem with diagram is not a strong issue.

**Comment by YannRobert** [comment]
> With statistics, we can click on diagram to see them bigger.

I never realized that !

> It works very bad, the diagrams move randomly in the screen.

Ok I can fix it

**Comment by YannRobert** [comment]
Ok, zoom-in and zoom-out on the line-chart and heatmap are fixed.

**Pull request merged**
