### PR TITLE
Complete Space Game (problem with threading handled)

### PR DESCRIPTION
**Pull request by hlong205**
Here is my game Space Game. Some code in there hasn't been used since I have a boss but its implementation seems to reduce the performance and might get the game crashed so I did not invoke any of its methods. The game works fine now and hopefully you can check and give me some opinions.

### CODE REVIEW

**Comment by hlong205** [comment]
I have the line "Untranslated" in the game thumbnail. I'm looking for a way to solve it.

**Comment by hlong205** [comment]
I run mvn clean install -T 1C -Dfindbugs.skip=false -DskipFormatterFormat=false -DskipFormatterValidate=false and it returns me a couple bugs. I already went debugging but there is no error or exception return with my current code or performance. I tried 2 solutions, one with the main JavaFx thread and another one with multithreading along with JavaFx thread.

**Comment by wafaahs** [comment]
> I run mvn clean install -T 1C -Dfindbugs.skip=false -DskipFormatterFormat=false -DskipFormatterValidate=false and it returns me a couple bugs. I already went debugging but there is no error or exception return with my current code or performance. I tried 2 solutions, one with the main JavaFx thread and another one with multithreading along with JavaFx thread.

@hlong205 
You need to run this command first: 
mvn clean install -T 1C
Then run: 
mvn clean install -T 1C -Dfindbugs.skip=false -DskipFormatterFormat=false -DskipFormatterValidate=false 

Also the untranslated means you have to add a translation in "multilinguism.csv"

**Comment by hlong205** [comment]
the first one mvn clean install -T 1C is perfectly fine. I succesfully run it. But the problem is with the second one

**Comment by hlong205** [comment]
I just made a pull request and the check is successful

**Pull request merged**
