### PR TITLE
shootingGamesStats : Added percentage to statistics for shooting games

### PR DESCRIPTION
**Pull request by Sannaraek**
This commit addresses issue #593

### CODE REVIEW

**Comment by schwabdidier** [comment]
@Sannaraek : next time add an explicit name for your pull request (for instance here, shootingGamesStats)

**Comment by schwabdidier** [comment]
Ok, I merge. But @Sannaraek there is an issue. At least in game bubble, it doesn't work. please check that point add an issue and resolve it.

**Comment by Sannaraek** [comment]
@schwabdidier I think this is due to the being that Bubble game was not an instance of shooting games, where the percentage was being tracked. I have made it so that percentage for bubble game will also appear with my next commit.
I have also noticed that the incGoalFunction of the bubble game is called twice while although it is only hit once (Using the same hit function as shooter games). This caused a bais with the percentage, and a bais with the total hit count statistics of the game. 
so specifically for the bubble game, I have incremented the statistic of the number of bubbles in the game 2 times to adjust this problem.

**Comment by schwabdidier** [comment]
There was a problem with Travis. It is because you did not make the complete commande line which is the very same on Travis (see https://github.com/schwabdidier/GazePlay/blob/master/CONTRIBUTE.MD). Do it always before pull request.

`mvn clean install -Dfindbugs.skip=false -DskipFormatterFormatFormat=false -DskipFormatterValidate=false`

**Pull request merged**
