### PR TITLE
Move Build over to Gradle + OpenJDK/JFX 11

### PR DESCRIPTION
**Pull request by Tohaker**
As detailed in Issues #878 and #879, this PR proposes to move the build over to Gradle from Maven. 
According to Travis builds:
Gradle: 
image
Maven (current master): 
image

Showing a 3 minute build time decrease, due to the parallelism of Gradle.

Local building of this version was done using AdoptOpenJDK, and OpenJFX is injected through a Gradle Plugin, meaning new developers can get up and running faster.

### CODE REVIEW

**Comment by schwabdidier** [comment]
Wow great job. This week end I am at Disneyland :) but I go through that on Monday !

**Comment by schwabdidier** [comment]
Just to know. Do we still have plugins like find bugs or format code ?

**Comment by Tohaker** [comment]
Findbugs is deprecated, it's been replaced with Spotbugs and works slightly differently. I had a go at adding it in but it seemed to struggle. I'll take another look tomorrow, for now Ive left it out. 
Enjoy Disneyland!

**Comment by Tohaker** [comment]
Issue #861 has been resolved in commit fa69942

**Comment by schwabdidier** [comment]
ok, I write comments when they come to me.

About what is produced, 
- in the gazeplay-project-1.6.2-SNAPSHOT, there is the tar, zip but it lacks the file version.
- we have only bin and lib. It lacks data and licenses
- in bin, we should have gazeplay.bat gazeplay-linux.sh gazeplay-macos.sh gazeplay-win10.bat

**Comment by Tohaker** [comment]
I have used Gradle extentions such as ShadowJar and FatJar to create all-in-one packages before, I can add it to this. 
Not sure about the other issues, could you point out where in Maven they are created? I may have missed a plugin.

**Comment by schwabdidier** [comment]
The plugin is in gazeplay-dist/pom.xml and description of generated archives in gazeplay-dist/descriptor.xml

**Comment by Tohaker** [comment]
Adding ShadowJar (or any other fat-jar type task) to Gradle is possible, however I'm struggling at the moment as this is a multi-module project.

**Comment by schwabdidier** [comment]
ok, I have two problems now :

- Findbugs finds bugs :)
- when I switch off Findbugs (I comment it in build.gradle), it produce only gazeplay.bat gazeplay-linux.sh gazeplay-macos.sh gazeplay-win10.bat files for now

**Comment by Tohaker** [comment]
You can keep the spotbugs plugin installed and just run `gradlew -x spotbugsMain -x spotbugsTest` to stop it running. Was it not finding bugs on Maven? We may just have to tell to alert to breaking bugs - it appears to be looking for everything.

**Comment by schwabdidier** [comment]
Ok, now, I see how to use it and how to avoid test
`./gradlew -x spotbugsMain -x spotbugsTest -Dorg.gradle.java.home="path_to_my_openJDK"`

**Comment by YannRobert** [comment]
Hi
Did you compare the artifacts produced by maven with the artifacts produced by gradle ?
You will see how the third parties libraries' License file were distributed.

Keep in mind that third parties license files are different from the GazePlay license file.
The licence maven plugin was only managing third parties libraries license files.

**Comment by YannRobert** [comment]
About Shadow Jar, my opinion is that I don't like it.
I think existing behavior having a "lib" directory containing multiple (many) dependencies is better.
This is not just a matter of taste. We could argue, do we need to ?
We should not mess with third parties libraries. They should be provided as is.

**Comment by schwabdidier** [comment]
Agree with Yann (sorry, very busy I didn't check last version of pull request today).

**Comment by schwabdidier** [comment]
Ok, I tested. I prefer the way we processed it previously with four folders :
bin 
data  
lib
licenses

One problems with launchers, we still have ${project.version} instead of the actual version

**Comment by Tohaker** [comment]
> Did you compare the artifacts produced by maven with the artifacts produced by gradle ?
My main justification for this whole PR is that the Maven build is very difficult to setup for a new contributor (or perhaps there are some steps not documented). This is mainly due to JavaFX no longer being included in Java, so one would have to manually link all the libraries together - this is not sustainable. Gradle, in my experience, simplifies this by encapsulating the whole project. If this worked using Maven, I'd have no quarrel. My point here is that I wasn't able to see how Maven produced artifacts, so have struggled to match it here.

> I think existing behavior having a "lib" directory containing multiple (many) dependencies is better.
This is fine, I got part-way there with Gradle but chose Shadow simply based on experience with the plugin. I will adjust to have all libraries separated.

**Comment by Tohaker** [comment]
From looking at the current release zip, this version looks a lot closer in both naming, structure and contents. The only major thing missing is the included JRE, which (in my opinion) should be installed for the user through an installer (I believe issue 602 will address this).

**Comment by schwabdidier** [comment]
Something lacks because now, we have only script in the distribution folder (zip is only 2ko)

**Comment by Tohaker** [comment]
May I know what command you ran? When I run `./gradlew clean packageApp` I get these two outputs:

**Comment by schwabdidier** [comment]
It is far better ! We are close to accept this pull request ! Great job !

Sorry I am new to gradle so I didn't use the appropriate commands. So, it works ! Everything is well packaged I think, licences seem ok (if you can, please double check that point @YannRobert ).

build is no more in the package dist but in a folder called build/distribution. It is not a problem for me.

Scripts are now well formed !

 It works very well when I specify my open jdk java path but not if I don't do it (it is on my mac but I the same problem on my Windows) :

`Executing command line: java -Xms256m -Xmx1g -jar ../lib/gazeplay-project-1.6.2-SNAPSHOT.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/gazeplay/GazePlayLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)`

@Tohaker can we use our "own" open java command to launch GazePlay ? It is a major problem for many users, that is why I added the JRE in last version.

One last point, I didn't check yet is the release plugin, does it work here ?

**Comment by Tohaker** [comment]
Odd, I don't have the same Java error on my Windows PC (I have yet to try it on MacOS). It looks like a PATH error, JRE 52 usually means you're on 1.8 - this uses 11.
I can probably get the minimal JRE packaged up with everything, I dislike doing it this way but I appreciate the users of the application may not have the technical knowledge to install it themselves. We should find a more sustainable method of distributing the JRE at another time.

I will start work on implementing the release plugin next :)

**Comment by schwabdidier** [comment]
In fact, my default JRE is 1.8 for now just to test this kind of things. I want JRE inside the applications because I know that some people say that GazePlay doesn't work just because there were not able to follow 2 steps.

**Comment by Tohaker** [comment]
(Ignore these commits, they were a test)

**Comment by Tohaker** [comment]
Release plugin is setup now. Will sort out the JRE tomorrow.

**Comment by Tohaker** [comment]
Tested on Windows with new JRE, works as expected and the JRE is now about half the size too, thanks to Modular JRE since JDK 9.
Mac also works fine, but the scripts for that rely on the default JAVA_HOME so we must assume this is set correctly for the user.

**Comment by schwabdidier** [comment]
I check that after lunch :)

**Comment by schwabdidier** [comment]
I have this problem on my win10 (where I just have java oracle installed

`2019-09-15 14:45:57,166 ERROR - Graphics Device initialization failed for :  d3d, sw
2019-09-15 14:45:57,166 ERROR - Error initializing QuantumRenderer: no suitable pipeline found
2019-09-15 14:45:57,167 ERROR - java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
2019-09-15 14:45:57,168 ERROR -         at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
2019-09-15 14:45:57,168 ERROR -         at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
2019-09-15 14:45:57,169 ERROR -         at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)

C:\Users\didie\Desktop\gazeplay-project-1.6.2-SNAPSHOT\gazeplay-project-1.6.2-SNAPSHOT\bin>REM prints a nice "Press any key to continue . . . " message

C:\Users\didie\Desktop\gazeplay-project-1.6.2-SNAPSHOT\gazeplay-project-1.6.2-SNAPSHOT\bin>pause
Appuyez sur une touche pour continuer...`

**Comment by schwabdidier** [comment]
Ok, I tried to add `targetCompatibility = '11'` in build.gradle but it doesn't work

**Comment by Tohaker** [comment]
That's strange, I'll see if I can replicate it on a non-dev windows machine.

**Comment by Tohaker** [comment]
I have referred to [this](https://github.com/javafxports/openjdk-jfx/issues/237#issuecomment-426909275) Github issue to resolve it.  I had to download the Jmods from [JavaFX](https://gluonhq.com/products/javafx/), install them to my own Jmods folder and then I used [this handy site](https://justinmahar.github.io/easyjre/) to generate the jlink command I needed to create the JRE distribution.
Please could you try to run it again - I have tested it on a Windows 10 machine that has never seen JavaFX in its lifetime and it worked first time.

**Comment by schwabdidier** [comment]
I test tomorrow afternoon !

**Comment by Tohaker** [comment]
JRE can also be created from scratch with a plugin, however there are a few manual steps involved when first initialising the project. If you like this method, we can take out the jre from git (~163MB) and make it part of the packaging task. This shifts a lot of the processing to the developer, but significantly increases the control we have over the distributed JRE. Currently, all the modules from the JRE are included, but I bet some could be removed for a slight space saving.

**Comment by schwabdidier** [comment]
For now, it is ok ! It works very well on my windows !

I check littles points but it seems quite ok for me.

**Comment by Tohaker** [comment]
Are there any further changes left before this PR can be approved?

**Comment by schwabdidier** [comment]
Sorry, I have a strong personal problem since yesterday, I didn't have enough time for that. It seems better but won't be able to manage request this morning.

**Comment by schwabdidier** [comment]
I experiment some problem with intellj, I can't run the program

**Comment by Tohaker** [comment]
Can you show an error message? I will take a look later - perhaps the `run` task has got mixed up.

**Comment by schwabdidier** [comment]
No error message. When I "right clic" GazePlayLauncher, I can't find run and when I want to "add configuration", I can't find my classes with a main...

**Comment by Tohaker** [comment]
Interesting... I can't seem to replicate it myself - when I right click on the same file I get this option: 
image
Can you try to run the `run` task from the Gradle side panel? 
image

**Comment by schwabdidier** [comment]
Ok, I am a little bit stupid... It was not the appropriate JDK... Now I obtain "Error: A JNI error has occurred, please check your installation and try again"

**Comment by schwabdidier** [comment]
Ok, it was almost the same problem :)

So everything but the release plugin seems ok ! I don't know how to test it without a release so...

**Comment by schwabdidier** [comment]
It  is ok for me ! Now I resolve "conflicts"

**Comment by schwabdidier** [comment]
congrat @Tohaker Very good work :)

**Pull request merged**
