### PR TITLE
Various refactorings

### PR DESCRIPTION
**Pull request by YannRobert**
refactorings on Configuration and GazePlayDirectories

### CODE REVIEW

**Comment by schwabdidier** [comment]
"translator should be notified when the config is changed..." What do you mean ?

**Comment by YannRobert** [comment]
config includes language, 
language affects translation, 
translator should be notified when the config is changed

**Comment by schwabdidier** [comment]
ok but how can we manage that ?

**Comment by YannRobert** [comment]
it's done already.

**Comment by schwabdidier** [comment]
ok, I think I misunderstood "translator", you don't want to say the man/woman who translate the list ?

**Comment by YannRobert** [comment]
Yes, I mean the Translator class.

**Comment by schwabdidier** [comment]
ok, professional misrepresentation :)

**Comment by schwabdidier** [comment]
Say to me, when I can merge :)

**Comment by YannRobert** [comment]
There is still a lot of bugs as reported by spotbugs in the gazeplay-games module.
But I think this is enough for this PR.

This is ready to be merge.

**Pull request merged**
