### PR TITLE
Sounds

### PR DESCRIPTION
**Pull request by WaffleBuffer**
Added volume level and music folder to the saved configuration. Also added "final" to some fields which can use it.
Heavily modified Background music to be able to have a list of music (as a playlist) (also having a map is not necessary because we can retrieve the music name with a MediaPlayer).
Added one line to multilinguisme but for some reasons the merge thought that everything was different (maybe due to some wrong format because one character was wrongly formatted).
I also added volume for where is it game so the volume level of the voices would correspond to the one set for background music. However, as said in issue #402, it would be better to have a separated volume controller for sound effects.

### CODE REVIEW

**Comment by YannRobert** [comment]
Please restore the Map of MediaPlayer

**Comment by WaffleBuffer** [comment]
Why ? It wasn't relevant to the new version. Also it was only to store the filename but it can be retrieve through the mediaplayer.

**Comment by YannRobert** [comment]
Please keep the background.music manager to manage the background music.
Sound effects should be managed by a separate controller, as indicated in #402

**Comment by WaffleBuffer** [comment]
The volume has been removed from whereisit game.

**Pull request merged**
