### PR TITLE
Configuration screen for magic card

### PR DESCRIPTION
**Pull request by WaffleBuffer**
I hope this time it is clean. I run the maven clean install command and also the git reset --soft then commit.
So this is just a cleaner (i hope) PR. It contains the code to add a configuration screen to the magic card game so there is no more multiple entries in the home screen. Some pictures could be added (like pictures of how cards will be).
I also added the CSS files that were not uploaded list time (now i'm using terminal for git and not netbeans interface).
However i did not change pom.xml because those changes where from netbeans. If it is a problem, i could revert it manually before a new PR and then add the file into a .gitignore which will only be local.

### CODE REVIEW

**Comment by WaffleBuffer** [comment]
I guess you could just cancel the last PR and review this one instead.

**Comment by schwabdidier** [comment]
What is your point of view @YannRobert ? On my side, I like, it is interesting. Would it be better if createGameModePane() was not in the game but in the general control side (for now in net.gazeplay).

**Comment by YannRobert** [comment]
> Would it be better if createGameModePane() was not in the game but in the general control side (for now in net.gazeplay).

Yes, the whole point is that if you make the chooser part of the game, then you must change every game to support that, also, when you exit the variant chooser without playing, you still get to see the stats screen, ...

**Comment by YannRobert** [comment]
@WaffleBuffer Please see #204

**Pull request closed without merging**
